version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: react-intl
    versions:
    - 5.13.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.9.0
