before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn
  - cd ./functions && npm install && cd ..
script:
  - yarn build
  - yarn lint
  - yarn stylelint
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
    repo: ricglz0201/ttt-react
  token:
    secure: "CfwKnxht0YmxDHF6mshm+o7HA4fWbqLJs+qgEPGo5Ow8EkHeFB1olJvr2EhDb0YGBxHke9riPLLaOugW/txrArgYkfaxsYPPNQWQiEJu8XIxwn4hHzE5vr5epZ8vWizNYTZ8QoFEwUpE/xkSGCHyvXXg937e386iLLceXwj9/2z8CLj+OIy0mE5JnkHx0z0kF+ue0xPytKNN8ZA/3NOi9bVycHlQmFVu1n1szCSKLVMiF3bjl0Icy/bpP3nq7mEcWokhvmodmxSmSf70L2CrT/mv/J1hvTPluKXHHcMk6vE3oDjxfTt7o+kQ+TkTGHTC0bIjdOukipMpMxem+xU9/372WfXFlPWelzgAn5nPdora895MYh+A9T2TLgQYAGJH1x3e8cY+ZvKB+bQdBq/CfLMK3dpgQ6PFmhvy69espWfyU9OpNquhJUMP/gnJBeve8S4DMETyhPHNjQgKS1XFj/irkQDzN2yYOGvLGgVUOYtYs05CgdBXGvq9Oukahaf82LbG75FxDBxkrQkEL9F2CT8wKrqoGAT/HypXDRhpFFpPpYZspTw/5V+4Y+4Tx3UqB9N/FcjZhqF873C5vLaogUk0Vohei+rVhOqe2WLMCf7eYN4veqKre3E1pFVqYubFvA9cDjDOVBLnB3OnC6xlKfXb3bWJgYzLj/12QS0jTjg="
